### ISSUE TITLE
No collected dev tools info

### ISSUE THREAD

**Issue by apizz** [munkireport/devtools#2]
Recently installed brew and the required XCode command line tools, and despite homebrew, homebrew_info, and devtools modules installed and on the latest versions, I'm not seeing any data out of devtools.

No errors appear as part manual `munkireportrunner` trigger.

Test Mac is a 16-in 2019 running 10.15.7 (19H15).

Let me know what additional information would be helpful to troubleshoot.

**Comment by apizz** [comment]
To be clear, homebrew modules are fine

**Comment by tuxudo** [comment]
Should be resolved with version v1.4 of this module.

**Comment by apizz** [comment]
Hmm ... I'm still seeing no data on the devtools page.  To be clear, updated the module on my munkireport host, reinstalled munkireport with latest module on test Mac, upgraded munkireport DB, and have manually run `munkireport-runner` several times.  I had installed CLI tools via brew before the change and subsequently installed XQuartz just to try something different.

Even after installing this additional software that should be reported, I'm unfortunately still seeing no returned data via device or listing view.

**Comment by tuxudo** [comment]
Should be fully resolved with v1.5 of the module.

**Comment by apizz** [comment]
1.5 doesn't seem to fix this for me either ...

**Comment by apizz** [comment]
In my case have this running in testing in Docker.  Connected to DB container, auth'd with root mysql account creds, changed to munkireport db, and ran `DELETE FROM hash WHERE hash.name = 'devtools';`.  Subsequent munkireport-runner run successfully reported & showed data.

Now should not be an issue on new builds.  Docker instances with current image will need to update the modules before completing first devtools report
